name: Require PRs for Specific Files

on:
  push:
    branches:
      - master

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Fetch the last two commits to ensure we have HEAD and HEAD~1

      - name: Check for specific files
        run: |
          # List of files or directories that should require PRs
          REQUIRED_PR_FILES=(
            "test.txt"
          )

          for file in "${REQUIRED_PR_FILES[@]}"; do
            if git diff --name-only HEAD~1 HEAD | grep -q "$file"; then
              echo "Direct commits to $file are not allowed. Please use a pull request."
              exit 1
            fi
          done
